receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp:
    endpoint: "jaeger:4317"   # Export traces to Jaeger OTLP gRPC receiver
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"

  logging: {}  # Logs to console with default verbosity

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, logging]

    metrics:
      receivers: [otlp]
      exporters: [prometheus, logging]

    logs:
      receivers: [otlp]
      exporters: [logging]
